[package]
name = "nc"
version = "0.1.0"
authors = ["Xu Shaohua <xushaohua2016@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
