[package]
name = "nc"
version = "0.4.11"
authors = ["Xu Shaohua <shaohua@biofan.org>"]
readme = "README.md"
homepage = "https://github.com/xushaohua/nc"
repository = "https://github.com/xushaohua/nc"
documentation = "https://docs.rs/nc"
description = "Execute system call directly"
edition = "2018"
license = "Apache-2.0"
publish = true
build = "build.rs"
keywords = ["syscall", "linux"]
categories = ["os", "no-std", "external-ffi-bindings"]
exclude = ["/.travis.yml", ".gitignore"]

[dependencies]
